describe('Display Tests', () => {
  it('Should be able to get all of these elements to assure they exist on page load', () => {
    cy.visit('http://localhost:3000/')
    .get('h1')
    .get('#stance')
    .get('#trick')
    .get('#obstacle')
    .get('#tutorial')
    .get('button')
    .get('.trick-card')
  })
})
describe('Form Tests',()=>{
  //note for instructors: ran out of time for writing intercept.
  it('Should take in user inputs and add an element that reflects these inputs.',()=>{
    cy.visit('http://localhost:3000/')
    .get('#stance')
    .select('regular')
    .get('#trick')
    .type('new trick')
    .get('#obstacle')
    .select('flat ground')
    .get('#tutorial')
    .type('youtube.com')
    .get('button')
    .click()
    .get('.tricks-container > :nth-child(4')
    .get('#4 > :nth-child(1)')
    .contains('regular')
    .get('#4 > :nth-child(2)')
    .contains('new trick')
    .get('#4 > :nth-child(3)')
    .contains('flat ground')
    .get('#4 > :nth-child(4)')
    .contains('youtube.com')

  })
})