describe('Display Tests', () => {
  it('Should be able to get all of these elements to assure they exist on page load', () => {
    cy.visit('http://localhost:3000/')
    .get('h1')
    .get('#stance')
    .get('#trick')
    .get('#obstacle')
    .get('#tutorial')
    .get('button')
    .get('.trick-card')
  })
})
describe('Form Tests',()=>{
  it('Should take in user inputs and add an element that reflects these inputs.',()=>{
    cy.visit('http://localhost:3000/')
    .get('#stance')
    .select('regular')
    .get('#trick')
    .type('new trick')
    .get('#obstacle')
    .select('flat ground')
    .get('#tutorial')
    .type('youtube.com')
    .get('button')
    .click()
    cy.get('.tricks-container > :nth-child(4')
  })
})